== Zig's wasm2c adapted for WAHE

This is link:https://github.com/ziglang/zig/tree/master/stage1[Zig's wasm2c] adapted to WAHE WebAssembly modules so they can be turned into native modules. All of my edits are marked with `WAHE edit` in the code.

Modifications:

- Added an `EXPORT` attribute.
- Added a way to call WAHE host's `wahe_run_command()`.
- Currently implemented some WASI functions as dummy functions, more work is needed there.
- The `memory` pointer is exported so it can be accessed by the WAHE host.
- Exported variables such as `\__heap_base` or `__data_end` are currently ignored whereas they caused the original wasm2c to stop everything.
- Functions have a comment added that shows its original position in the .wasm file which helps with debugging because each function can be identified using the original module's `.map` file. For example: `static void f71(void) {	// source pos b44a` which matches the `.map` file entry that reads `-     b44a       1d                 long_double_not_supported`.
- The section skipping starts by rewinding the file pointer so that sections can be read out of order.

=== Compilation and usage

As with the original you can simply compile it by doing `clang wasm2c.c -o wasm2c.exe` and then use it by doing `wasm2c $1.wasm $1_trans.c`.

Then you can compile the transpiled file into a native module for instance by doing this: `clang $1_trans.c -o $1_trans.dll -shared -Os`.
